export default {
  "resizePanel": "Drag the bottom edge to adjust height",
  "errorPanelHeightSave": "Panel height could not be saved: {reason}",
  "waitingListUpdate": "Waiting for X to update the list. Progress is retained.",
  "language": "Language",
  "panel": "Fake Friend",
  "subtitle": "See the connection. Make your choice.",
  "close": "Hide panel",
  "seen": "Accounts found",
  "pending": "To review",
  "removed": "Unfollowed",
  "countdown": "Next round",
  "loading": "Loading settings…",
  "scan": "Scan following",
  "pause": "Pause",
  "resume": "Resume",
  "stop": "Stop",
  "review": "Review one by one",
  "controls": "Run controls",
  "tabs": "Cleanup options",
  "keep": "Keep list",
  "settings": "Settings",
  "list": "This run",
  "keepHint": "Additions and removals are saved automatically.",
  "keepPlaceholder": "@account_to_keep",
  "maxActions": "Unfollow limit",
  "skipFirst": "Skip first N accounts",
  "scanMin": "Scan min. seconds",
  "scanMax": "Scan max. seconds",
  "unfollowMin": "Unfollow min. seconds",
  "unfollowMax": "Unfollow max. seconds",
  "autoScroll": "Scroll the list automatically",
  "pacingHint": "Scan from top to bottom. Random waits alternate between short and long. Pause keeps your progress.",
  "reviewHint": "Check this account on X. Approval adds it to the list; unfollowing starts later.",
  "reviewChanged": "The connection has changed. Keep or skip this account.",
  "approve": "Add to cleanup list",
  "addKeep": "Add to keep list",
  "skip": "Skip",
  "start": "Start cleanup",
  "footer": "Local only · Current connections",
  "export": "Export activity",
  "stayTitle": "You can switch tabs. Don’t refresh or navigate away.",
  "empty": "Accounts to review will appear here after scanning.",
  "reviewPosition": "{current} / {total} · Review",
  "executeCount": "Start · {count} approved",
  "unknown": "Unknown account",
  "confirmed": "Approved",
  "skipped": "Skipped",
  "protected": "Skipped at start",
  "seconds": "{count} s",
  "scanFirst": "Scan the list, then review each account.",
  "skipChanged": "Skip count changed. Scan and review again.",
  "keepSaved": "Keep list saved. Review the cleanup list again.",
  "reviewDone": "{count} accounts approved. Select Start cleanup to unfollow.",
  "locating": "Finding @{handle}…",
  "located": "Found @{handle}. Check it on X.",
  "decisionSaved": "Saved @{handle}. {count} accounts remain to review.",
  "locatingPaused": "Finding accounts paused.",
  "scanned": "Found {count} accounts.",
  "scannedSkip": "Found {count} accounts; skipped the first {skip}.",
  "processing": "Processing @{handle}…",
  "removedUser": "Unfollowed @{handle}.",
  "skippedUser": "Skipped @{handle}.",
  "nextRound": "Next round in {count} s.",
  "finishedMax": "Unfollow limit reached.",
  "finishedVisible": "Loaded accounts processed.",
  "finishedEnd": "End of the available list. Run finished.",
  "finishedApproved": "This batch is complete. You can choose more accounts.",
  "resumed": "Resumed.",
  "paused": "Paused.",
  "stopped": "Stopped.",
  "waitEnd": "Checking list end ({count}/2).",
  "errorBusy": "Finish or stop the current action first.",
  "errorMode": "Invalid operation.",
  "errorReview": "Review the accounts before starting.",
  "errorNoResume": "There is no paused run to resume.",
  "errorAccount": "The signed-in account changed. Stopped.",
  "errorLoading": "Account data is still loading. Wait and scan again.",
  "errorPage": "Open your own Following page on X.",
  "errorPageStructure": "Cannot identify the Following list. Refresh X and try again.",
  "errorButton": "Cannot identify the account button.",
  "errorIdentity": "Account identity does not match.",
  "errorDialog": "Cannot verify the unfollow confirmation dialog. Stopped.",
  "errorOtherDialog": "Close the existing dialog before continuing.",
  "errorMoved": "The account moved or changed. Scan again.",
  "errorChanged": "The connection changed. Keep or skip this account.",
  "errorUnconfirmed": "Unfollow result is unconfirmed. Check X before retrying.",
  "errorScroll": "Scrolling did not finish. Stopped.",
  "errorTop": "Could not return to the top. Check the page.",
  "errorLoadTimeout": "List loading did not finish. The end is not confirmed.",
  "errorStuck": "Scrolling did not advance. Scan stopped.",
  "errorRange": "Use whole seconds: 1 ≤ minimum < maximum ≤ 10000.",
  "errorRandom": "Could not select a wait interval. Stopped.",
  "errorSkipRange": "Skip count must be an integer from 0 to 10000.",
  "errorActionRange": "Unfollow limit must be an integer from 1 to 10000.",
  "errorAutoScroll": "Select whether to scroll automatically.",
  "errorStorage": "Invalid local settings. Check extension storage.",
  "errorNoAudit": "No activity record has been started.",
  "errorCurrent": "Review the account currently shown.",
  "errorNotListed": "This account is not in the current list.",
  "errorNoCandidates": "No accounts need review.",
  "errorEmpty": "The approved list is empty.",
  "errorInvalidHandle": "Invalid handle: {value}",
  "errorPageAlert": "Stopped — X reports: {reason}",
  "errorOutcome": "Unfollow clicked; result unconfirmed: {reason}",
  "errorSave": "Could not save the record: {reason}",
  "errorMissingHandle": "Cannot locate @{handle}. Scan again.",
  "errorNavigation": "Could not open the page. Refresh X and try again.",
  "errorLogin": "Sign in to X, wait for the page, then try again.",
  "errorLeft": "You left the page. Navigation cancelled.",
  "acknowledge": "Got it",
  "popupState": "Check the page",
  "popupErrorTitle": "Unable to open",
  "popupErrorMessage": "Resolve the issue below, then try again.",
  "opening": "Opening…",
  "goFollowing": "Open my Following list",
  "popupReady": "Ready · Waiting for the page",
  "popupTitle": "Open your Following list",
  "checking": "Checking the page…",
  "preparing": "Preparing the cleanup panel",
  "checkingMessage": "Please wait while the page is checked.",
  "pageState": "Current page status",
  "helpOpen": "Use the button below to open your Following list.",
  "helpLogin": "If signed out of X, sign in and select the button again.",
  "helpPanel": "The panel appears first. You can scan once the list has loaded.",
  "popupFooter": "Detects your account · Runs locally",
  "navigationError": "Unable to navigate",
  "fakeFriend": "Fake friend",
  "needsCheck": "Needs checking",
  "skipShort": "Skip",
  "backupMenu": "Backup & restore",
  "exportBackup": "Export backup",
  "importKeep": "Import whitelist",
  "keepImported": "Whitelist imported: {count} accounts added. Review choices were reset; please review again.",
  "errorImportJson": "The backup file is not valid JSON.",
  "errorImportFormat": "The backup whitelist format is invalid.",
  "errorImportOwner": "The backup has no whitelist for the current account. Choose a file exported from this account.",
  "removeKeep": "Remove",
  "keepEmpty": "No accounts in the whitelist yet.",
  "keepRemoved": "@{handle} was removed from the whitelist and the change was saved automatically.",
  "errorKeepProfile": "The whitelist avatar and name data is invalid.",
  "openingFollowing": "Opening your Following list…",
  "errorExtensionReload": "The extension was reloaded or removed. The old task has stopped. Refresh X.",
  "errorStalePanel": "An older extension task is still on this page. Refresh X, then reopen the extension."
};
