export default {
  "resizePanel": "Arrastra el borde inferior para ajustar la altura",
  "errorPanelHeightSave": "No se pudo guardar la altura del panel: {reason}",
  "waitingListUpdate": "Esperando que X actualice la lista. Se conserva el progreso.",
  "language": "Idioma",
  "panel": "Fake Friend",
  "subtitle": "Comprende la relación. Decide después.",
  "close": "Ocultar panel",
  "seen": "Cuentas encontradas",
  "pending": "Por revisar",
  "removed": "Dejadas de seguir",
  "countdown": "Próxima ronda",
  "loading": "Cargando ajustes…",
  "scan": "Buscar seguidos",
  "pause": "Pausar",
  "resume": "Continuar",
  "stop": "Detener",
  "review": "Revisar una a una",
  "controls": "Controles de ejecución",
  "tabs": "Opciones de limpieza",
  "keep": "Conservar",
  "settings": "Ajustes",
  "list": "Esta ejecución",
  "keepHint": "Las cuentas añadidas o eliminadas se guardan automáticamente.",
  "keepPlaceholder": "@cuenta_a_conservar",
  "maxActions": "Límite de bajas",
  "skipFirst": "Omitir primeras N cuentas",
  "scanMin": "Escaneo mínimo / s",
  "scanMax": "Escaneo máximo / s",
  "unfollowMin": "Baja mínima / s",
  "unfollowMax": "Baja máxima / s",
  "autoScroll": "Desplazar automáticamente",
  "pacingHint": "Escanea de arriba abajo. Alterna esperas aleatorias cortas y largas. Pausar conserva el progreso.",
  "reviewHint": "Revisa esta cuenta en X. Aprobar solo la añade a la lista; la limpieza comienza después.",
  "reviewChanged": "La relación cambió. Conserva u omite esta cuenta.",
  "approve": "Añadir a limpieza",
  "addKeep": "Añadir a conservados",
  "skip": "Omitir",
  "start": "Iniciar limpieza",
  "footer": "Solo local · Relaciones actuales",
  "export": "Exportar actividad",
  "stayTitle": "Puedes cambiar de pestaña. No recargues ni salgas de esta página.",
  "empty": "Aquí aparecerán las cuentas después del escaneo.",
  "reviewPosition": "{current} / {total} · Revisar",
  "executeCount": "Iniciar · {count} aprobadas",
  "unknown": "Cuenta desconocida",
  "confirmed": "Aprobada",
  "skipped": "Omitida",
  "protected": "Omitida al inicio",
  "seconds": "{count} s",
  "scanFirst": "Escanea la lista y revisa las cuentas.",
  "skipChanged": "Cambió el número a omitir. Escanea y revisa de nuevo.",
  "keepSaved": "Lista guardada. Revisa de nuevo la lista de limpieza.",
  "reviewDone": "{count} cuentas aprobadas. Pulsa Iniciar limpieza para dejar de seguirlas.",
  "locating": "Buscando @{handle}…",
  "located": "Encontrada @{handle}. Revísala en X.",
  "decisionSaved": "Guardada @{handle}. Quedan {count} cuentas por revisar.",
  "locatingPaused": "Búsqueda pausada.",
  "scanned": "Se encontraron {count} cuentas.",
  "scannedSkip": "Se encontraron {count} cuentas; se omitieron las primeras {skip}.",
  "processing": "Procesando @{handle}…",
  "removedUser": "Dejaste de seguir a @{handle}.",
  "skippedUser": "Se omitió @{handle}.",
  "nextRound": "Próxima ronda en {count} s.",
  "finishedMax": "Se alcanzó el límite de bajas.",
  "finishedVisible": "Cuentas cargadas procesadas.",
  "finishedEnd": "Fin de la lista disponible. Ejecución terminada.",
  "finishedApproved": "Esta tanda ha terminado. Puedes elegir más cuentas.",
  "resumed": "Reanudado.",
  "paused": "En pausa.",
  "stopped": "Detenido.",
  "waitEnd": "Comprobando el final ({count}/2).",
  "errorBusy": "Termina o detén la acción actual.",
  "errorMode": "Operación no válida.",
  "errorReview": "Revisa las cuentas antes de comenzar.",
  "errorNoResume": "No hay una ejecución pausada.",
  "errorAccount": "Cambió la cuenta conectada. Detenido.",
  "errorLoading": "Los datos siguen cargando. Espera y vuelve a escanear.",
  "errorPage": "Abre tu propia lista de seguidos en X.",
  "errorPageStructure": "No se reconoce la lista. Recarga X e inténtalo de nuevo.",
  "errorButton": "No se reconoce el botón de la cuenta.",
  "errorIdentity": "La identidad de la cuenta no coincide.",
  "errorDialog": "No se puede verificar la confirmación. Detenido.",
  "errorOtherDialog": "Cierra el diálogo abierto antes de continuar.",
  "errorMoved": "La cuenta cambió o se movió. Escanea de nuevo.",
  "errorChanged": "La relación cambió. Conserva u omite la cuenta.",
  "errorUnconfirmed": "Resultado sin confirmar. Compruébalo en X antes de reintentar.",
  "errorScroll": "El desplazamiento no terminó. Detenido.",
  "errorTop": "No se pudo volver al inicio. Revisa la página.",
  "errorLoadTimeout": "La lista no terminó de cargar. Final sin confirmar.",
  "errorStuck": "El desplazamiento no avanzó. Escaneo detenido.",
  "errorRange": "Segundos enteros: 1 ≤ mínimo < máximo ≤ 10000.",
  "errorRandom": "No se pudo elegir el intervalo. Detenido.",
  "errorSkipRange": "Omitir requiere un entero de 0 a 10000.",
  "errorActionRange": "El límite requiere un entero de 1 a 10000.",
  "errorAutoScroll": "Elige si deseas desplazar automáticamente.",
  "errorStorage": "Ajustes locales no válidos. Revisa el almacenamiento.",
  "errorNoAudit": "No se ha iniciado un registro.",
  "errorCurrent": "Revisa la cuenta que se muestra.",
  "errorNotListed": "Esta cuenta no está en la lista actual.",
  "errorNoCandidates": "No hay cuentas por revisar.",
  "errorEmpty": "La lista aprobada está vacía.",
  "errorInvalidHandle": "Usuario no válido: {value}",
  "errorPageAlert": "Detenido — X informa: {reason}",
  "errorOutcome": "Se pulsó dejar de seguir; resultado sin confirmar: {reason}",
  "errorSave": "No se pudo guardar el registro: {reason}",
  "errorMissingHandle": "No se encuentra @{handle}. Escanea de nuevo.",
  "errorNavigation": "No se pudo abrir la página. Recarga X e inténtalo de nuevo.",
  "errorLogin": "Inicia sesión en X, espera y vuelve a intentarlo.",
  "errorLeft": "Saliste de la página. Navegación cancelada.",
  "acknowledge": "Entendido",
  "popupState": "Revisa la página",
  "popupErrorTitle": "No se puede abrir",
  "popupErrorMessage": "Resuelve el problema indicado y vuelve a intentarlo.",
  "opening": "Abriendo…",
  "goFollowing": "Abrir mis seguidos",
  "popupReady": "Listo · Esperando la página",
  "popupTitle": "Abre tu lista de seguidos",
  "checking": "Comprobando la página…",
  "preparing": "Preparando la limpieza",
  "checkingMessage": "Espera mientras se comprueba la página.",
  "pageState": "Estado de la página",
  "helpOpen": "Usa el botón para abrir tu lista de seguidos.",
  "helpLogin": "Si no has iniciado sesión en X, hazlo y pulsa de nuevo.",
  "helpPanel": "El panel aparece primero. Puedes escanear cuando se cargue la lista.",
  "popupFooter": "Detecta tu cuenta · Funciona localmente",
  "navigationError": "No se puede navegar",
  "fakeFriend": "Falso amigo",
  "needsCheck": "Revisar",
  "skipShort": "Omitir",
  "backupMenu": "Copia y restauración",
  "exportBackup": "Exportar copia",
  "importKeep": "Importar lista blanca",
  "keepImported": "Lista blanca importada: {count} cuentas añadidas. Se restablecieron las decisiones; revisa de nuevo.",
  "errorImportJson": "El archivo de copia no es un JSON válido.",
  "errorImportFormat": "El formato de la lista blanca de la copia no es válido.",
  "errorImportOwner": "La copia no contiene la lista blanca de la cuenta actual. Elige un archivo exportado desde esta cuenta.",
  "removeKeep": "Quitar",
  "keepEmpty": "La lista blanca está vacía.",
  "keepRemoved": "Se quitó a @{handle} de la lista blanca y el cambio se guardó automáticamente.",
  "errorKeepProfile": "Los datos de avatar y nombre de la lista blanca no son válidos.",
  "openingFollowing": "Abriendo tu lista de seguidos…",
  "errorExtensionReload": "La extensión se recargó o eliminó. La tarea anterior se detuvo. Recarga X.",
  "errorStalePanel": "Esta página aún contiene una tarea de la extensión anterior. Recarga X y vuelve a abrir la extensión."
};
