export default {
  "resizePanel": "Faites glisser le bord inférieur pour régler la hauteur",
  "errorPanelHeightSave": "Impossible d’enregistrer la hauteur du panneau : {reason}",
  "waitingListUpdate": "En attente de la mise à jour de la liste par X. Progression conservée.",
  "language": "Langue",
  "panel": "Fake Friend",
  "subtitle": "Comprendre le lien. Puis décider.",
  "close": "Masquer le panneau",
  "seen": "Comptes trouvés",
  "pending": "À vérifier",
  "removed": "Désabonnements",
  "countdown": "Prochain passage",
  "loading": "Chargement…",
  "scan": "Analyser la liste",
  "pause": "Pause",
  "resume": "Reprendre",
  "stop": "Arrêter",
  "review": "Vérifier un par un",
  "controls": "Commandes",
  "tabs": "Options de nettoyage",
  "keep": "À conserver",
  "settings": "Réglages",
  "list": "Cette session",
  "keepHint": "Les ajouts et les retraits sont enregistrés automatiquement.",
  "keepPlaceholder": "@compte_a_conserver",
  "maxActions": "Limite de désabonnements",
  "skipFirst": "Ignorer les N premiers",
  "scanMin": "Analyse min. / s",
  "scanMax": "Analyse max. / s",
  "unfollowMin": "Désabonnement min. / s",
  "unfollowMax": "Désabonnement max. / s",
  "autoScroll": "Défilement automatique",
  "pacingHint": "Analyse de haut en bas. Les attentes alternent entre courtes et longues, au hasard. La pause conserve la progression.",
  "reviewHint": "Vérifiez ce compte sur X. L'approbation l'ajoute à la liste ; le nettoyage démarre ensuite.",
  "reviewChanged": "La relation a changé. Conservez ou ignorez ce compte.",
  "approve": "Ajouter au nettoyage",
  "addKeep": "Ajouter aux conservés",
  "skip": "Ignorer",
  "start": "Lancer le nettoyage",
  "footer": "En local · Relations actuelles",
  "export": "Exporter le journal",
  "stayTitle": "Vous pouvez changer d’onglet. Ne rechargez pas et ne quittez pas cette page.",
  "empty": "Les comptes apparaîtront ici après l'analyse.",
  "reviewPosition": "{current} / {total} · Vérification",
  "executeCount": "Démarrer · {count} approuvés",
  "unknown": "Compte inconnu",
  "confirmed": "Approuvé",
  "skipped": "Ignoré",
  "protected": "Ignoré au début",
  "seconds": "{count} s",
  "scanFirst": "Analysez la liste, puis vérifiez les comptes.",
  "skipChanged": "Le nombre à ignorer a changé. Relancez l'analyse.",
  "keepSaved": "Liste enregistrée. Vérifiez à nouveau la liste de nettoyage.",
  "reviewDone": "{count} comptes approuvés. Lancez le nettoyage pour vous désabonner.",
  "locating": "Recherche de @{handle}…",
  "located": "@{handle} trouvé. Vérifiez sur X.",
  "decisionSaved": "Choix enregistré pour @{handle}. Encore {count} comptes à vérifier.",
  "locatingPaused": "Recherche en pause.",
  "scanned": "{count} comptes trouvés.",
  "scannedSkip": "{count} comptes trouvés ; les {skip} premiers ignorés.",
  "processing": "Traitement de @{handle}…",
  "removedUser": "Désabonné de @{handle}.",
  "skippedUser": "@{handle} ignoré.",
  "nextRound": "Prochain passage dans {count} s.",
  "finishedMax": "Limite de désabonnements atteinte.",
  "finishedVisible": "Comptes chargés traités.",
  "finishedEnd": "Fin de la liste disponible. Session terminée.",
  "finishedApproved": "Ce lot est terminé. Vous pouvez sélectionner d’autres comptes.",
  "resumed": "Repris.",
  "paused": "En pause.",
  "stopped": "Arrêté.",
  "waitEnd": "Vérification de la fin ({count}/2).",
  "errorBusy": "Terminez ou arrêtez l'action actuelle.",
  "errorMode": "Opération non valide.",
  "errorReview": "Vérifiez les comptes avant de commencer.",
  "errorNoResume": "Aucune session en pause.",
  "errorAccount": "Le compte connecté a changé. Arrêt.",
  "errorLoading": "Chargement en cours. Patientez et relancez l'analyse.",
  "errorPage": "Ouvrez votre propre liste Abonnements sur X.",
  "errorPageStructure": "Liste non reconnue. Actualisez X et réessayez.",
  "errorButton": "Bouton du compte non reconnu.",
  "errorIdentity": "L'identité du compte ne correspond pas.",
  "errorDialog": "Confirmation impossible à vérifier. Arrêt.",
  "errorOtherDialog": "Fermez la boîte de dialogue ouverte.",
  "errorMoved": "Le compte a changé ou s'est déplacé. Relancez l'analyse.",
  "errorChanged": "La relation a changé. Conservez ou ignorez le compte.",
  "errorUnconfirmed": "Résultat non confirmé. Vérifiez sur X avant de réessayer.",
  "errorScroll": "Défilement inachevé. Arrêt.",
  "errorTop": "Retour en haut impossible. Vérifiez la page.",
  "errorLoadTimeout": "Chargement inachevé. Fin non confirmée.",
  "errorStuck": "Le défilement n'avance pas. Analyse arrêtée.",
  "errorRange": "Secondes entières : 1 ≤ minimum < maximum ≤ 10000.",
  "errorRandom": "Intervalle impossible à choisir. Arrêt.",
  "errorSkipRange": "Le nombre à ignorer doit être entier, de 0 à 10000.",
  "errorActionRange": "La limite doit être entière, de 1 à 10000.",
  "errorAutoScroll": "Choisissez le défilement automatique ou manuel.",
  "errorStorage": "Réglages locaux invalides. Vérifiez le stockage.",
  "errorNoAudit": "Aucun journal d'activité démarré.",
  "errorCurrent": "Vérifiez le compte affiché.",
  "errorNotListed": "Ce compte ne figure pas dans cette liste.",
  "errorNoCandidates": "Aucun compte à vérifier.",
  "errorEmpty": "La liste approuvée est vide.",
  "errorInvalidHandle": "Identifiant invalide : {value}",
  "errorPageAlert": "Arrêt — X indique : {reason}",
  "errorOutcome": "Désabonnement cliqué ; résultat non confirmé : {reason}",
  "errorSave": "Enregistrement impossible : {reason}",
  "errorMissingHandle": "@{handle} introuvable. Relancez l'analyse.",
  "errorNavigation": "Ouverture impossible. Actualisez X et réessayez.",
  "errorLogin": "Connectez-vous à X, patientez et réessayez.",
  "errorLeft": "Vous avez quitté la page. Navigation annulée.",
  "acknowledge": "Compris",
  "popupState": "Vérifiez la page",
  "popupErrorTitle": "Ouverture impossible",
  "popupErrorMessage": "Résolvez le problème ci-dessous, puis réessayez.",
  "opening": "Ouverture…",
  "goFollowing": "Ouvrir mes abonnements",
  "popupReady": "Prêt · En attente de la page",
  "popupTitle": "Ouvrez vos abonnements",
  "checking": "Vérification de la page…",
  "preparing": "Préparation du nettoyage",
  "checkingMessage": "Patientez pendant la vérification.",
  "pageState": "État de la page",
  "helpOpen": "Utilisez le bouton pour ouvrir vos abonnements.",
  "helpLogin": "Connectez-vous à X si nécessaire, puis recliquez.",
  "helpPanel": "Le panneau apparaît d’abord. Vous pouvez analyser une fois la liste chargée.",
  "popupFooter": "Compte détecté · Exécution locale",
  "navigationError": "Navigation impossible",
  "fakeFriend": "Faux ami",
  "needsCheck": "À contrôler",
  "skipShort": "Ignorer",
  "backupMenu": "Sauvegarde et restauration",
  "exportBackup": "Exporter la sauvegarde",
  "importKeep": "Importer la liste blanche",
  "keepImported": "Liste blanche importée : {count} comptes ajoutés. Les choix de vérification ont été réinitialisés ; vérifiez à nouveau.",
  "errorImportJson": "Le fichier de sauvegarde ne contient pas de JSON valide.",
  "errorImportFormat": "Le format de la liste blanche sauvegardée est invalide.",
  "errorImportOwner": "La sauvegarde ne contient aucune liste blanche pour le compte actuel. Choisissez un fichier exporté depuis ce compte.",
  "removeKeep": "Retirer",
  "keepEmpty": "La liste blanche est vide.",
  "keepRemoved": "@{handle} a été retiré de la liste blanche et la modification a été enregistrée automatiquement.",
  "errorKeepProfile": "Les données des avatars et des noms de la liste blanche sont invalides.",
  "openingFollowing": "Ouverture de votre liste d’abonnements…",
  "errorExtensionReload": "L’extension a été rechargée ou supprimée. L’ancienne tâche est arrêtée. Actualisez X.",
  "errorStalePanel": "Une tâche de l’ancienne extension est encore présente sur cette page. Actualisez X puis rouvrez l’extension."
};
