export default {
  "waitingListUpdate": "Ana jiran X ya sabunta jerin. An adana ci gaba.",
  "language": "Harshe",
  "panel": "Fake Friend",
  "subtitle": "Fahimci alaƙa. Sannan ka yanke shawara.",
  "close": "Ɓoye allon",
  "seen": "Asusun da aka gano",
  "pending": "Na dubawa",
  "removed": "An daina bi",
  "countdown": "Zagaye na gaba",
  "loading": "Ana loda saituna…",
  "scan": "Bincika masu bi",
  "pause": "Dakata",
  "resume": "Ci gaba",
  "stop": "Dakatar",
  "review": "Duba ɗaya bayan ɗaya",
  "controls": "Sarrafa aiki",
  "tabs": "Zaɓuɓɓukan tsabtacewa",
  "keep": "Na kiyayewa",
  "settings": "Saituna",
  "list": "Wannan zagaye",
  "keepHint": "Ana ajiye ƙari da cirewa ta atomatik.",
  "keepPlaceholder": "@asusu_na_kiyaye",
  "maxActions": "Iyakar daina bi",
  "skipFirst": "Tsallake N na farko",
  "scanMin": "Bincike mafi gajarta / s",
  "scanMax": "Bincike mafi tsawo / s",
  "unfollowMin": "Daina bi mafi gajarta / s",
  "unfollowMax": "Daina bi mafi tsawo / s",
  "autoScroll": "Gungura jerin kai tsaye",
  "pacingHint": "Bincika daga sama zuwa ƙasa. Lokutan jira na bazata suna sauyawa gajere da dogo. Dakatawa tana kiyaye ci gaba.",
  "reviewHint": "Duba asusun a X. Amincewa tana ƙara shi cikin jerin; daina bi zai faru daga baya.",
  "reviewChanged": "Alaƙar ta canza. Kiyaye ko tsallake asusun.",
  "approve": "Ƙara cikin tsabtacewa",
  "addKeep": "Ƙara cikin na kiyayewa",
  "skip": "Tsallake",
  "start": "Fara tsabtacewa",
  "footer": "A na'urarka · Alaƙoƙin yanzu",
  "export": "Fitar da tarihin aiki",
  "stayTitle": "Za ka iya sauya tab. Kada ka sabunta ko ka bar wannan shafin.",
  "empty": "Asusun za su bayyana a nan bayan bincike.",
  "reviewPosition": "{current} / {total} · Dubawa",
  "executeCount": "Fara · An amince da {count}",
  "unknown": "Asusu da ba a gane ba",
  "confirmed": "An amince",
  "skipped": "An tsallake",
  "protected": "An tsallake a farko",
  "seconds": "Dakika {count}",
  "scanFirst": "Bincika jerin, sannan duba kowane asusu.",
  "skipChanged": "Adadin tsallakewa ya canza. Sake bincika.",
  "keepSaved": "An ajiye jerin. Sake duba jerin tsabtacewa.",
  "reviewDone": "An amince da asusu {count}. Fara tsabtacewa don daina bi.",
  "locating": "Ana neman @{handle}…",
  "located": "An gano @{handle}. Duba a X.",
  "decisionSaved": "An ajiye zaɓin @{handle}. Akwai sauran {count}.",
  "locatingPaused": "An dakatar da neman asusu na ɗan lokaci.",
  "scanned": "An gano asusu {count}.",
  "scannedSkip": "An gano {count}; an tsallake {skip} na farko.",
  "processing": "Ana aiki kan @{handle}…",
  "removedUser": "An daina bin @{handle}.",
  "skippedUser": "An tsallake @{handle}.",
  "nextRound": "Zagaye na gaba bayan dakika {count}.",
  "finishedMax": "An kai iyakar daina bi.",
  "finishedVisible": "An gama asusun da aka loda.",
  "finishedEnd": "An kai ƙarshen jerin. An gama aiki.",
  "finishedApproved": "An kammala wannan rukuni. Za ka iya zaɓar wasu asusu.",
  "resumed": "An ci gaba.",
  "paused": "An dakata.",
  "stopped": "An dakatar.",
  "waitEnd": "Ana duba ƙarshen jerin ({count}/2).",
  "errorBusy": "Kammala ko dakatar da aikin yanzu.",
  "errorMode": "Aiki bai dace ba.",
  "errorReview": "Duba asusun kafin farawa.",
  "errorNoResume": "Babu aikin da aka dakata don ci gaba.",
  "errorAccount": "Asusun shiga ya canza. An dakatar.",
  "errorLoading": "Ana loda bayanai. Jira sannan sake bincika.",
  "errorPage": "Buɗe jerin waɗanda kake bi a X.",
  "errorPageStructure": "Ba a gane jerin ba. Sake loda X.",
  "errorButton": "Ba a gane maɓallin asusu ba.",
  "errorIdentity": "Shaidar asusu ba ta dace ba.",
  "errorDialog": "Ba a tabbatar da akwatin amincewa ba. An dakatar.",
  "errorOtherDialog": "Rufe akwatin da yake buɗe tukuna.",
  "errorMoved": "Asusun ya canza ko ya motsa. Sake bincika.",
  "errorChanged": "Alaƙar ta canza. Kiyaye ko tsallake asusun.",
  "errorUnconfirmed": "Ba a tabbatar da sakamako ba. Duba X kafin sake gwadawa.",
  "errorScroll": "Gungurawa bai gama ba. An dakatar.",
  "errorTop": "Ba a koma sama ba. Duba shafin.",
  "errorLoadTimeout": "Lodawa bai gama ba. Ba a tabbatar da ƙarshe ba.",
  "errorStuck": "Gungurawa bai ci gaba ba. An dakatar da bincike.",
  "errorRange": "Cikakkun dakiku: 1 ≤ mafi ƙanƙanta < mafi girma ≤ 10000.",
  "errorRandom": "Ba a zaɓi lokacin jira ba. An dakatar.",
  "errorSkipRange": "Adadin tsallakewa ya zama cikakken lamba 0–10000.",
  "errorActionRange": "Iyaka ta zama cikakken lamba 1–10000.",
  "errorAutoScroll": "Zaɓi ko za a gungura kai tsaye.",
  "errorStorage": "Saitunan na'ura ba su dace ba. Duba ma'ajiyar ƙarin.",
  "errorNoAudit": "Ba a fara tarihin aiki ba.",
  "errorCurrent": "Duba asusun da ake nunawa.",
  "errorNotListed": "Asusun baya cikin jerin yanzu.",
  "errorNoCandidates": "Babu asusun dubawa.",
  "errorEmpty": "Jerin da aka amince babu komai.",
  "errorInvalidHandle": "Sunan asusu bai dace ba: {value}",
  "errorPageAlert": "An dakatar — saƙon X: {reason}",
  "errorOutcome": "An danna daina bi; sakamako bai tabbata ba: {reason}",
  "errorSave": "Ba a ajiye tarihin ba: {reason}",
  "errorMissingHandle": "Ba a gano @{handle} ba. Sake bincika.",
  "errorNavigation": "Ba a buɗe shafin ba. Sake loda X.",
  "errorLogin": "Shiga X, jira lodawa sannan sake gwadawa.",
  "errorLeft": "Ka fita daga shafin. An soke sauyawa.",
  "acknowledge": "Na gane",
  "popupState": "Duba shafin",
  "popupErrorTitle": "Ba a iya buɗewa",
  "popupErrorMessage": "Gyara matsalar da ke ƙasa sannan sake gwadawa.",
  "opening": "Ana buɗewa…",
  "goFollowing": "Buɗe waɗanda nake bi",
  "popupReady": "A shirye · Ana jiran shafi",
  "popupTitle": "Buɗe jerin waɗanda kake bi",
  "checking": "Ana duba shafin…",
  "preparing": "Ana shirya tsabtacewa",
  "checkingMessage": "Jira yayin duba shafin.",
  "pageState": "Halin shafi",
  "helpOpen": "Danna maɓallin don buɗe jerin waɗanda kake bi.",
  "helpLogin": "Idan ba ka shiga X ba, shiga sannan danna kuma.",
  "helpPanel": "Allon zai bayyana da farko. Za ka iya fara bincike bayan jerin ya gama lodi.",
  "popupFooter": "Gano asusu · Aiki a na'urarka",
  "navigationError": "Ba a iya sauya shafi",
  "fakeFriend": "Abokin ƙarya",
  "needsCheck": "A duba",
  "skipShort": "Tsallake",
  "backupMenu": "Ajiyar madadin da maidowa",
  "exportBackup": "Fitar da ajiyar madadin",
  "importKeep": "Shigo da jerin amintattu",
  "keepImported": "An shigo da jerin amintattu: an ƙara asusu {count}. An sake saita zaɓin dubawa; a sake dubawa.",
  "errorImportJson": "Fayil ɗin ajiyar madadin ba ingantaccen JSON ba ne.",
  "errorImportFormat": "Tsarin jerin amintattu a ajiyar madadin bai inganta ba.",
  "errorImportOwner": "Ajiyar madadin ba ta da jerin amintattu na asusun yanzu. Zaɓi fayil da aka fitar daga wannan asusun.",
  "removeKeep": "Cire",
  "keepEmpty": "Babu asusu a jerin amintattu tukuna.",
  "keepRemoved": "An cire @{handle} daga jerin amintattu kuma an ajiye canjin ta atomatik.",
  "errorKeepProfile": "Bayanan hotuna da sunaye na jerin amintattu ba su inganta ba.",
  "openingFollowing": "Ana buɗe jerin waɗanda kake bi…",
  "errorExtensionReload": "An sake loda ko cire ƙarin. Tsohon aikin ya tsaya. Sabunta X.",
  "errorStalePanel": "Har yanzu akwai aikin tsohon ƙarin a wannan shafin. Sabunta X, sannan sake buɗe ƙarin."
};
