export default {
  "resizePanel": "Tarik tepi bawah untuk mengubah tinggi",
  "errorPanelHeightSave": "Tinggi panel tidak dapat disimpan: {reason}",
  "waitingListUpdate": "Menunggu X memperbarui daftar. Progres tetap tersimpan.",
  "language": "Bahasa",
  "panel": "Fake Friend",
  "subtitle": "Pahami hubungan. Tentukan pilihan.",
  "close": "Sembunyikan panel",
  "seen": "Akun ditemukan",
  "pending": "Perlu ditinjau",
  "removed": "Berhenti diikuti",
  "countdown": "Putaran berikutnya",
  "loading": "Memuat pengaturan…",
  "scan": "Pindai mengikuti",
  "pause": "Jeda",
  "resume": "Lanjutkan",
  "stop": "Hentikan",
  "review": "Tinjau satu per satu",
  "controls": "Kontrol proses",
  "tabs": "Opsi pembersihan",
  "keep": "Pertahankan",
  "settings": "Pengaturan",
  "list": "Proses ini",
  "keepHint": "Penambahan dan penghapusan disimpan otomatis.",
  "keepPlaceholder": "@akun_yang_dipertahankan",
  "maxActions": "Batas berhenti mengikuti",
  "skipFirst": "Lewati N akun pertama",
  "scanMin": "Pindai minimum / detik",
  "scanMax": "Pindai maksimum / detik",
  "unfollowMin": "Berhenti minimum / detik",
  "unfollowMax": "Berhenti maksimum / detik",
  "autoScroll": "Gulir daftar otomatis",
  "pacingHint": "Pindai dari atas ke bawah. Jeda acak bergantian pendek dan panjang. Menjeda mempertahankan progres.",
  "reviewHint": "Periksa akun ini di X. Persetujuan hanya menambahkannya ke daftar; pembersihan dimulai nanti.",
  "reviewChanged": "Hubungan berubah. Pertahankan atau lewati akun ini.",
  "approve": "Tambah ke pembersihan",
  "addKeep": "Tambah ke daftar tetap",
  "skip": "Lewati",
  "start": "Mulai pembersihan",
  "footer": "Lokal · Hubungan saat ini",
  "export": "Ekspor aktivitas",
  "stayTitle": "Boleh berganti tab. Jangan muat ulang atau tinggalkan halaman ini.",
  "empty": "Akun akan muncul di sini setelah dipindai.",
  "reviewPosition": "{current} / {total} · Tinjau",
  "executeCount": "Mulai · {count} disetujui",
  "unknown": "Akun tidak dikenal",
  "confirmed": "Disetujui",
  "skipped": "Dilewati",
  "protected": "Dilewati di awal",
  "seconds": "{count} dtk",
  "scanFirst": "Pindai daftar, lalu tinjau setiap akun.",
  "skipChanged": "Jumlah yang dilewati berubah. Pindai dan tinjau ulang.",
  "keepSaved": "Daftar disimpan. Tinjau ulang daftar pembersihan.",
  "reviewDone": "{count} akun disetujui. Pilih Mulai pembersihan untuk berhenti mengikuti.",
  "locating": "Mencari @{handle}…",
  "located": "@{handle} ditemukan. Periksa di X.",
  "decisionSaved": "Pilihan @{handle} disimpan. Tersisa {count} akun.",
  "locatingPaused": "Pencarian akun dijeda.",
  "scanned": "Menemukan {count} akun.",
  "scannedSkip": "Menemukan {count} akun; melewati {skip} pertama.",
  "processing": "Memproses @{handle}…",
  "removedUser": "Berhenti mengikuti @{handle}.",
  "skippedUser": "Melewati @{handle}.",
  "nextRound": "Putaran berikutnya dalam {count} dtk.",
  "finishedMax": "Batas berhenti mengikuti tercapai.",
  "finishedVisible": "Akun yang dimuat telah diproses.",
  "finishedEnd": "Akhir daftar yang tersedia. Proses selesai.",
  "finishedApproved": "Batch ini selesai. Anda dapat memilih akun lainnya.",
  "resumed": "Dilanjutkan.",
  "paused": "Dijeda.",
  "stopped": "Dihentikan.",
  "waitEnd": "Memeriksa akhir daftar ({count}/2).",
  "errorBusy": "Selesaikan atau hentikan tindakan saat ini.",
  "errorMode": "Operasi tidak valid.",
  "errorReview": "Tinjau akun sebelum memulai.",
  "errorNoResume": "Tidak ada proses yang dijeda.",
  "errorAccount": "Akun masuk berubah. Dihentikan.",
  "errorLoading": "Data akun masih dimuat. Tunggu lalu pindai ulang.",
  "errorPage": "Buka daftar Mengikuti milik Anda di X.",
  "errorPageStructure": "Daftar tidak dikenali. Muat ulang X dan coba lagi.",
  "errorButton": "Tombol akun tidak dikenali.",
  "errorIdentity": "Identitas akun tidak cocok.",
  "errorDialog": "Dialog konfirmasi tidak dapat diverifikasi. Dihentikan.",
  "errorOtherDialog": "Tutup dialog yang terbuka dahulu.",
  "errorMoved": "Akun berubah atau berpindah. Pindai ulang.",
  "errorChanged": "Hubungan berubah. Pertahankan atau lewati akun.",
  "errorUnconfirmed": "Hasil belum dikonfirmasi. Periksa X sebelum mencoba lagi.",
  "errorScroll": "Pengguliran belum selesai. Dihentikan.",
  "errorTop": "Tidak dapat kembali ke atas. Periksa halaman.",
  "errorLoadTimeout": "Daftar belum selesai dimuat. Akhir belum dikonfirmasi.",
  "errorStuck": "Pengguliran tidak maju. Pemindaian dihentikan.",
  "errorRange": "Detik bulat: 1 ≤ minimum < maksimum ≤ 10000.",
  "errorRandom": "Tidak dapat memilih interval. Dihentikan.",
  "errorSkipRange": "Jumlah yang dilewati harus bulat antara 0 dan 10000.",
  "errorActionRange": "Batas harus bulat antara 1 dan 10000.",
  "errorAutoScroll": "Pilih apakah akan menggulir otomatis.",
  "errorStorage": "Pengaturan lokal tidak valid. Periksa penyimpanan.",
  "errorNoAudit": "Catatan aktivitas belum dimulai.",
  "errorCurrent": "Tinjau akun yang sedang ditampilkan.",
  "errorNotListed": "Akun ini tidak ada dalam daftar saat ini.",
  "errorNoCandidates": "Tidak ada akun untuk ditinjau.",
  "errorEmpty": "Daftar persetujuan kosong.",
  "errorInvalidHandle": "Nama akun tidak valid: {value}",
  "errorPageAlert": "Dihentikan — pesan X: {reason}",
  "errorOutcome": "Tombol berhenti mengikuti ditekan; hasil belum dikonfirmasi: {reason}",
  "errorSave": "Tidak dapat menyimpan catatan: {reason}",
  "errorMissingHandle": "@{handle} tidak ditemukan. Pindai ulang.",
  "errorNavigation": "Halaman tidak terbuka. Muat ulang X dan coba lagi.",
  "errorLogin": "Masuk ke X, tunggu halaman, lalu coba lagi.",
  "errorLeft": "Anda meninggalkan halaman. Navigasi dibatalkan.",
  "acknowledge": "Mengerti",
  "popupState": "Periksa halaman",
  "popupErrorTitle": "Tidak dapat membuka",
  "popupErrorMessage": "Atasi masalah di bawah, lalu coba lagi.",
  "opening": "Membuka…",
  "goFollowing": "Buka daftar Mengikuti saya",
  "popupReady": "Siap · Menunggu halaman",
  "popupTitle": "Buka daftar Mengikuti Anda",
  "checking": "Memeriksa halaman…",
  "preparing": "Menyiapkan panel pembersihan",
  "checkingMessage": "Tunggu saat halaman diperiksa.",
  "pageState": "Status halaman",
  "helpOpen": "Gunakan tombol untuk membuka daftar Mengikuti Anda.",
  "helpLogin": "Jika belum masuk ke X, masuk lalu tekan lagi.",
  "helpPanel": "Panel muncul terlebih dahulu. Anda dapat memindai setelah daftar dimuat.",
  "popupFooter": "Deteksi akun · Berjalan lokal",
  "navigationError": "Tidak dapat menavigasi",
  "fakeFriend": "Teman palsu",
  "needsCheck": "Perlu diperiksa",
  "skipShort": "Lewati",
  "backupMenu": "Cadangkan & pulihkan",
  "exportBackup": "Ekspor cadangan",
  "importKeep": "Impor daftar putih",
  "keepImported": "Daftar putih diimpor: {count} akun ditambahkan. Pilihan peninjauan direset; tinjau kembali.",
  "errorImportJson": "File cadangan bukan JSON yang valid.",
  "errorImportFormat": "Format daftar putih dalam cadangan tidak valid.",
  "errorImportOwner": "Cadangan tidak memuat daftar putih akun saat ini. Pilih file yang diekspor dari akun ini.",
  "removeKeep": "Hapus",
  "keepEmpty": "Belum ada akun dalam daftar putih.",
  "keepRemoved": "@{handle} dihapus dari daftar putih dan perubahan disimpan otomatis.",
  "errorKeepProfile": "Data avatar dan nama dalam daftar putih tidak valid.",
  "openingFollowing": "Membuka daftar Mengikuti Anda…",
  "errorExtensionReload": "Ekstensi dimuat ulang atau dihapus. Tugas lama telah berhenti. Muat ulang X.",
  "errorStalePanel": "Halaman ini masih memuat tugas ekstensi versi lama. Muat ulang X, lalu buka kembali ekstensi."
};
