export default {
  "waitingListUpdate": "X のリスト更新を待っています。進捗は保持されています。",
  "language": "言語",
  "panel": "Fake Friend",
  "subtitle": "つながりを確かめて、選ぼう。",
  "close": "パネルを隠す",
  "seen": "検出したアカウント",
  "pending": "確認待ち",
  "removed": "解除済み",
  "countdown": "次の処理まで",
  "loading": "設定を読み込み中…",
  "scan": "フォローを調べる",
  "pause": "一時停止",
  "resume": "再開",
  "stop": "停止",
  "review": "一件ずつ確認",
  "controls": "実行操作",
  "tabs": "整理メニュー",
  "keep": "保持リスト",
  "settings": "設定",
  "list": "今回の一覧",
  "keepHint": "追加と削除は自動的に保存されます。",
  "keepPlaceholder": "@保持するアカウント",
  "maxActions": "解除数の上限",
  "skipFirst": "先頭 N 件を除外",
  "scanMin": "確認の最短間隔 / 秒",
  "scanMax": "確認の最長間隔 / 秒",
  "unfollowMin": "解除の最短間隔 / 秒",
  "unfollowMax": "解除の最長間隔 / 秒",
  "autoScroll": "一覧を自動スクロール",
  "pacingHint": "先頭から末尾まで確認します。短い待機と長い待機を交互にランダム設定します。一時停止で進捗を保持します。",
  "reviewHint": "X 上のアカウントを確認してください。承認すると一覧に追加され、解除は後で実行します。",
  "reviewChanged": "フォロー関係が変わりました。保持するかスキップしてください。",
  "approve": "整理リストに追加",
  "addKeep": "保持リストに追加",
  "skip": "スキップ",
  "start": "解除を実行",
  "footer": "ローカル処理 · 現在の関係",
  "export": "操作記録を出力",
  "stayTitle": "タブの切り替えは可能です。このページの再読み込み・移動は控えてください。",
  "empty": "確認後、対象のアカウントがここに表示されます。",
  "reviewPosition": "{current} / {total} · 確認",
  "executeCount": "実行 · {count} 件承認済み",
  "unknown": "不明なアカウント",
  "confirmed": "承認済み",
  "skipped": "スキップ済み",
  "protected": "先頭から除外",
  "seconds": "{count} 秒",
  "scanFirst": "一覧を調べてから、一件ずつ確認してください。",
  "skipChanged": "除外数が変わりました。もう一度一覧を確認してください。",
  "keepSaved": "保持リストを保存しました。整理リストを再確認してください。",
  "reviewDone": "{count} 件を承認しました。「解除を実行」で解除します。",
  "locating": "@{handle} を探しています…",
  "located": "@{handle} を見つけました。X 上で確認してください。",
  "decisionSaved": "@{handle} の選択を保存しました。残り {count} 件です。",
  "locatingPaused": "アカウント検索を一時停止しました。",
  "scanned": "{count} 件を検出しました。",
  "scannedSkip": "{count} 件を検出し、先頭 {skip} 件を除外しました。",
  "processing": "@{handle} を処理中…",
  "removedUser": "@{handle} のフォローを解除しました。",
  "skippedUser": "@{handle} をスキップしました。",
  "nextRound": "次の処理まで {count} 秒。",
  "finishedMax": "解除数の上限に達しました。",
  "finishedVisible": "読み込み済みの範囲を処理しました。",
  "finishedEnd": "読み込める一覧の末尾です。完了しました。",
  "finishedApproved": "今回の処理が完了しました。続けてほかのアカウントを選択できます。",
  "resumed": "再開しました。",
  "paused": "一時停止しました。",
  "stopped": "停止しました。",
  "waitEnd": "一覧の末尾を確認中（{count}/2）。",
  "errorBusy": "現在の操作を完了または停止してください。",
  "errorMode": "無効な操作です。",
  "errorReview": "開始前にアカウントを確認してください。",
  "errorNoResume": "再開できる処理がありません。",
  "errorAccount": "ログイン中のアカウントが変わったため停止しました。",
  "errorLoading": "アカウントを読み込み中です。待ってから再確認してください。",
  "errorPage": "X で自分のフォロー一覧を開いてください。",
  "errorPageStructure": "フォロー一覧を認識できません。X を再読み込みしてください。",
  "errorButton": "アカウントのボタンを認識できません。",
  "errorIdentity": "アカウント情報が一致しません。",
  "errorDialog": "解除確認画面を確認できず停止しました。",
  "errorOtherDialog": "開いているダイアログを閉じてください。",
  "errorMoved": "アカウントが移動または変更されました。再確認してください。",
  "errorChanged": "関係が変わりました。保持またはスキップしてください。",
  "errorUnconfirmed": "解除結果が不明です。再試行の前に X 上で確認してください。",
  "errorScroll": "スクロールが完了せず停止しました。",
  "errorTop": "先頭に戻れませんでした。ページを確認してください。",
  "errorLoadTimeout": "読み込み未完了です。末尾は未確認です。",
  "errorStuck": "スクロールが進まず確認を停止しました。",
  "errorRange": "整数秒で 1 ≤ 最小値 < 最大値 ≤ 10000 にしてください。",
  "errorRandom": "待機時間を選べず停止しました。",
  "errorSkipRange": "除外数は 0～10000 の整数にしてください。",
  "errorActionRange": "解除数の上限は 1～10000 の整数にしてください。",
  "errorAutoScroll": "自動スクロールの有無を選んでください。",
  "errorStorage": "ローカル設定が不正です。拡張機能の保存領域を確認してください。",
  "errorNoAudit": "操作記録がまだありません。",
  "errorCurrent": "表示中のアカウントを確認してください。",
  "errorNotListed": "今回の一覧にないアカウントです。",
  "errorNoCandidates": "確認するアカウントはありません。",
  "errorEmpty": "承認済みの一覧が空です。",
  "errorInvalidHandle": "無効なユーザー名：{value}",
  "errorPageAlert": "停止しました。X の通知：{reason}",
  "errorOutcome": "フォロー解除を押しましたが結果は未確認です：{reason}",
  "errorSave": "記録を保存できませんでした：{reason}",
  "errorMissingHandle": "@{handle} が見つかりません。再確認してください。",
  "errorNavigation": "ページを開けません。X を再読み込みしてください。",
  "errorLogin": "X にログインし、読み込みを待ってから再試行してください。",
  "errorLeft": "ページを離れたため移動を取り消しました。",
  "acknowledge": "了解",
  "popupState": "ページを確認してください",
  "popupErrorTitle": "開けません",
  "popupErrorMessage": "下記の問題を解決して再試行してください。",
  "opening": "開いています…",
  "goFollowing": "自分のフォロー一覧へ",
  "popupReady": "準備完了 · ページ待機中",
  "popupTitle": "フォロー一覧を開いてください",
  "checking": "ページを確認中…",
  "preparing": "整理パネルを準備中",
  "checkingMessage": "ページの確認が終わるまでお待ちください。",
  "pageState": "ページの状態",
  "helpOpen": "下のボタンで自分のフォロー一覧を開きます。",
  "helpLogin": "未ログインなら X にログインして再度押してください。",
  "helpPanel": "先にパネルが表示されます。リストの読み込み後にスキャンできます。",
  "popupFooter": "アカウント自動認識 · ローカル実行",
  "navigationError": "移動できません",
  "fakeFriend": "偽の友達",
  "needsCheck": "要確認",
  "skipShort": "スキップ",
  "backupMenu": "バックアップと復元",
  "exportBackup": "バックアップを出力",
  "importKeep": "ホワイトリストを読み込む",
  "keepImported": "ホワイトリストを読み込み、{count} 件追加しました。確認内容をリセットしました。再度確認してください。",
  "errorImportJson": "バックアップファイルは有効な JSON ではありません。",
  "errorImportFormat": "バックアップ内のホワイトリストの形式が正しくありません。",
  "errorImportOwner": "バックアップに現在のアカウントのホワイトリストがありません。このアカウントから出力したファイルを選んでください。",
  "removeKeep": "削除",
  "keepEmpty": "ホワイトリストは空です。",
  "keepRemoved": "@{handle} をホワイトリストから削除し、変更を自動保存しました。",
  "errorKeepProfile": "ホワイトリストのアバターと名前のデータが正しくありません。",
  "openingFollowing": "フォロー一覧を開いています…",
  "errorExtensionReload": "拡張機能が再読み込みまたは削除されました。以前の処理を停止しました。X を再読み込みしてください。",
  "errorStalePanel": "このページには古い拡張機能の処理が残っています。X を再読み込みしてから拡張機能を開いてください。"
};
