export default {
  "waitingListUpdate": "We dey wait make X update di list. Your progress still dey.",
  "language": "Language",
  "panel": "Fake Friend",
  "subtitle": "Check the connection. Na you go decide.",
  "close": "Hide panel",
  "seen": "Accounts we find",
  "pending": "Ones to check",
  "removed": "Don unfollow",
  "countdown": "Next round",
  "loading": "Settings dey load…",
  "scan": "Scan following",
  "pause": "Pause",
  "resume": "Continue",
  "stop": "Stop",
  "review": "Check one by one",
  "controls": "Run controls",
  "tabs": "Cleanup options",
  "keep": "Keep list",
  "settings": "Settings",
  "list": "This round",
  "keepHint": "Anything wey you add or remove go save by itself.",
  "keepPlaceholder": "@account_to_keep",
  "maxActions": "Unfollow limit",
  "skipFirst": "Skip first N accounts",
  "scanMin": "Scan least seconds",
  "scanMax": "Scan most seconds",
  "unfollowMin": "Unfollow least seconds",
  "unfollowMax": "Unfollow most seconds",
  "autoScroll": "Scroll the list by itself",
  "pacingHint": "Scan from top reach bottom. Short and long random waits go take turns. Pause go keep your progress.",
  "reviewHint": "Check this account for X. Approve go only add am to list; unfollow go happen later.",
  "reviewChanged": "The connection don change. Keep or skip this account.",
  "approve": "Add to cleanup list",
  "addKeep": "Add to keep list",
  "skip": "Skip",
  "start": "Start cleanup",
  "footer": "Na here e dey run · Current connections",
  "export": "Export activity record",
  "stayTitle": "You fit change tab. No refresh or leave this page.",
  "empty": "Accounts to check go show here after scan.",
  "reviewPosition": "{current} / {total} · Check",
  "executeCount": "Start · {count} approved",
  "unknown": "Account we no know",
  "confirmed": "Approved",
  "skipped": "Skipped",
  "protected": "Skipped for beginning",
  "seconds": "{count} s",
  "scanFirst": "Scan the list, then check each account.",
  "skipChanged": "Skip number don change. Scan and check again.",
  "keepSaved": "Keep list don save. Check cleanup list again.",
  "reviewDone": "You don approve {count} accounts. Press Start cleanup to unfollow.",
  "locating": "We dey find @{handle}…",
  "located": "We don find @{handle}. Check am for X.",
  "decisionSaved": "Choice for @{handle} don save. {count} accounts remain.",
  "locatingPaused": "Account search don pause.",
  "scanned": "We find {count} accounts.",
  "scannedSkip": "We find {count} accounts; skip the first {skip}.",
  "processing": "We dey process @{handle}…",
  "removedUser": "You don unfollow @{handle}.",
  "skippedUser": "We skip @{handle}.",
  "nextRound": "Next round na after {count} s.",
  "finishedMax": "Unfollow don reach limit.",
  "finishedVisible": "We don finish the accounts wey load.",
  "finishedEnd": "Available list don end. This round don finish.",
  "finishedApproved": "This batch don finish. You fit choose more accounts.",
  "resumed": "E don continue.",
  "paused": "E don pause.",
  "stopped": "E don stop.",
  "waitEnd": "We dey check list end ({count}/2).",
  "errorBusy": "Finish or stop wetin dey run first.",
  "errorMode": "This operation no correct.",
  "errorReview": "Check the accounts before you start.",
  "errorNoResume": "No paused run dey to continue.",
  "errorAccount": "The account wey sign in don change. We don stop.",
  "errorLoading": "Account data still dey load. Wait, then scan again.",
  "errorPage": "Open your own Following list for X.",
  "errorPageStructure": "We no fit identify the list. Refresh X and try again.",
  "errorButton": "We no fit identify the account button.",
  "errorIdentity": "Account identity no match.",
  "errorDialog": "We no fit confirm the unfollow box. We don stop.",
  "errorOtherDialog": "Close the box wey dey open first.",
  "errorMoved": "Account don move or change. Scan again.",
  "errorChanged": "Connection don change. Keep or skip the account.",
  "errorUnconfirmed": "Result never confirm. Check X before you try again.",
  "errorScroll": "Scrolling no finish. We don stop.",
  "errorTop": "We no fit return to top. Check the page.",
  "errorLoadTimeout": "List never finish loading. End never confirm.",
  "errorStuck": "Scrolling no move forward. Scan don stop.",
  "errorRange": "Use whole seconds: 1 ≤ minimum < maximum ≤ 10000.",
  "errorRandom": "We no fit choose wait time. We don stop.",
  "errorSkipRange": "Skip number must be whole number from 0 to 10000.",
  "errorActionRange": "Unfollow limit must be whole number from 1 to 10000.",
  "errorAutoScroll": "Choose whether make list scroll by itself.",
  "errorStorage": "Local settings no correct. Check extension storage.",
  "errorNoAudit": "Activity record never start.",
  "errorCurrent": "Check the account wey show now.",
  "errorNotListed": "This account no dey this list.",
  "errorNoCandidates": "No account need checking.",
  "errorEmpty": "Approved list dey empty.",
  "errorInvalidHandle": "This handle no correct: {value}",
  "errorPageAlert": "We don stop — X talk say: {reason}",
  "errorOutcome": "We don press unfollow; result never confirm: {reason}",
  "errorSave": "We no fit save record: {reason}",
  "errorMissingHandle": "We no find @{handle}. Scan again.",
  "errorNavigation": "Page no open. Refresh X and try again.",
  "errorLogin": "Sign in to X, wait for page, then try again.",
  "errorLeft": "You don comot for page. Navigation don cancel.",
  "acknowledge": "I don hear",
  "popupState": "Check the page",
  "popupErrorTitle": "E no fit open",
  "popupErrorMessage": "Fix the matter below, then try again.",
  "opening": "E dey open…",
  "goFollowing": "Open my Following list",
  "popupReady": "Ready · We dey wait for page",
  "popupTitle": "Open your Following list",
  "checking": "We dey check page…",
  "preparing": "We dey prepare cleanup panel",
  "checkingMessage": "Wait small make we check the page.",
  "pageState": "How the page dey",
  "helpOpen": "Use the button below to open your Following list.",
  "helpLogin": "If you never sign in to X, sign in and press again.",
  "helpPanel": "The panel go show first. You fit scan once the list don load.",
  "popupFooter": "E dey find your account · Na here e dey run",
  "navigationError": "E no fit change page",
  "fakeFriend": "Fake friend",
  "needsCheck": "Need checking",
  "skipShort": "Skip",
  "backupMenu": "Backup & restore",
  "exportBackup": "Export backup",
  "importKeep": "Import whitelist",
  "keepImported": "Whitelist don enter: {count} accounts join. Review choices don reset; check them again.",
  "errorImportJson": "The backup file no be valid JSON.",
  "errorImportFormat": "The whitelist format for the backup no correct.",
  "errorImportOwner": "The backup no get whitelist for this account. Choose file wey you export from this account.",
  "removeKeep": "Remove",
  "keepEmpty": "No account dey whitelist yet.",
  "keepRemoved": "@{handle} don comot from whitelist and the change don save by itself.",
  "errorKeepProfile": "The whitelist picture and name data no correct.",
  "openingFollowing": "Your Following list dey open…",
  "errorExtensionReload": "Extension don reload or comot. Old task don stop. Refresh X.",
  "errorStalePanel": "Old extension task still dey this page. Refresh X, then open the extension again."
};
