export default {
  "waitingListUpdate": "Aguardando o X atualizar a lista. O progresso foi mantido.",
  "language": "Idioma",
  "panel": "Fake Friend",
  "subtitle": "Entenda a conexão. Faça sua escolha.",
  "close": "Ocultar painel",
  "seen": "Contas encontradas",
  "pending": "Para revisar",
  "removed": "Deixou de seguir",
  "countdown": "Próxima rodada",
  "loading": "Carregando ajustes…",
  "scan": "Verificar seguindo",
  "pause": "Pausar",
  "resume": "Continuar",
  "stop": "Parar",
  "review": "Revisar uma a uma",
  "controls": "Controles",
  "tabs": "Opções de limpeza",
  "keep": "Manter",
  "settings": "Ajustes",
  "list": "Esta execução",
  "keepHint": "Adições e remoções são salvas automaticamente.",
  "keepPlaceholder": "@conta_para_manter",
  "maxActions": "Limite de remoções",
  "skipFirst": "Pular primeiras N contas",
  "scanMin": "Verificação mín. / s",
  "scanMax": "Verificação máx. / s",
  "unfollowMin": "Remoção mín. / s",
  "unfollowMax": "Remoção máx. / s",
  "autoScroll": "Rolar automaticamente",
  "pacingHint": "Verifica de cima a baixo. Alterna esperas aleatórias curtas e longas. A pausa mantém o progresso.",
  "reviewHint": "Confira esta conta no X. Aprovar apenas inclui na lista; a limpeza começa depois.",
  "reviewChanged": "A relação mudou. Mantenha ou pule esta conta.",
  "approve": "Adicionar à limpeza",
  "addKeep": "Adicionar para manter",
  "skip": "Pular",
  "start": "Iniciar limpeza",
  "footer": "Somente local · Relações atuais",
  "export": "Exportar atividades",
  "stayTitle": "Pode mudar de aba. Não atualize nem saia desta página.",
  "empty": "As contas aparecerão aqui após a verificação.",
  "reviewPosition": "{current} / {total} · Revisão",
  "executeCount": "Iniciar · {count} aprovadas",
  "unknown": "Conta desconhecida",
  "confirmed": "Aprovada",
  "skipped": "Ignorada",
  "protected": "Ignorada no início",
  "seconds": "{count} s",
  "scanFirst": "Verifique a lista e revise cada conta.",
  "skipChanged": "O número a pular mudou. Verifique novamente.",
  "keepSaved": "Lista salva. Revise novamente a lista de limpeza.",
  "reviewDone": "{count} contas aprovadas. Inicie a limpeza para deixar de seguir.",
  "locating": "Localizando @{handle}…",
  "located": "@{handle} encontrada. Confira no X.",
  "decisionSaved": "Escolha de @{handle} salva. Faltam {count} contas.",
  "locatingPaused": "Localização pausada.",
  "scanned": "{count} contas encontradas.",
  "scannedSkip": "{count} contas encontradas; primeiras {skip} ignoradas.",
  "processing": "Processando @{handle}…",
  "removedUser": "Deixou de seguir @{handle}.",
  "skippedUser": "@{handle} ignorada.",
  "nextRound": "Próxima rodada em {count} s.",
  "finishedMax": "Limite de remoções atingido.",
  "finishedVisible": "Contas carregadas processadas.",
  "finishedEnd": "Fim da lista disponível. Execução concluída.",
  "finishedApproved": "Este lote foi concluído. Você pode escolher mais contas.",
  "resumed": "Retomado.",
  "paused": "Pausado.",
  "stopped": "Parado.",
  "waitEnd": "Confirmando o fim ({count}/2).",
  "errorBusy": "Conclua ou pare a ação atual.",
  "errorMode": "Operação inválida.",
  "errorReview": "Revise as contas antes de começar.",
  "errorNoResume": "Não há execução pausada.",
  "errorAccount": "A conta conectada mudou. Interrompido.",
  "errorLoading": "Dados carregando. Aguarde e verifique novamente.",
  "errorPage": "Abra sua própria lista Seguindo no X.",
  "errorPageStructure": "Lista não reconhecida. Atualize o X e tente novamente.",
  "errorButton": "Botão da conta não identificado.",
  "errorIdentity": "A identidade da conta não corresponde.",
  "errorDialog": "Não foi possível verificar a confirmação. Interrompido.",
  "errorOtherDialog": "Feche a caixa de diálogo aberta.",
  "errorMoved": "A conta mudou ou saiu da página. Verifique novamente.",
  "errorChanged": "A relação mudou. Mantenha ou pule a conta.",
  "errorUnconfirmed": "Resultado não confirmado. Confira no X antes de tentar novamente.",
  "errorScroll": "A rolagem não terminou. Interrompido.",
  "errorTop": "Não foi possível voltar ao topo. Confira a página.",
  "errorLoadTimeout": "Carregamento incompleto. Fim não confirmado.",
  "errorStuck": "A rolagem não avançou. Verificação interrompida.",
  "errorRange": "Segundos inteiros: 1 ≤ mínimo < máximo ≤ 10000.",
  "errorRandom": "Não foi possível escolher o intervalo. Interrompido.",
  "errorSkipRange": "O número a pular deve ser inteiro de 0 a 10000.",
  "errorActionRange": "O limite deve ser inteiro de 1 a 10000.",
  "errorAutoScroll": "Escolha se deseja rolar automaticamente.",
  "errorStorage": "Ajustes locais inválidos. Confira o armazenamento.",
  "errorNoAudit": "Nenhum registro de atividades iniciado.",
  "errorCurrent": "Revise a conta exibida.",
  "errorNotListed": "Esta conta não está na lista atual.",
  "errorNoCandidates": "Nenhuma conta para revisar.",
  "errorEmpty": "A lista aprovada está vazia.",
  "errorInvalidHandle": "Usuário inválido: {value}",
  "errorPageAlert": "Interrompido — o X informa: {reason}",
  "errorOutcome": "Botão de deixar de seguir acionado; resultado não confirmado: {reason}",
  "errorSave": "Não foi possível salvar: {reason}",
  "errorMissingHandle": "@{handle} não encontrada. Verifique novamente.",
  "errorNavigation": "Não foi possível abrir. Atualize o X e tente novamente.",
  "errorLogin": "Entre no X, aguarde e tente novamente.",
  "errorLeft": "Você saiu da página. Navegação cancelada.",
  "acknowledge": "Entendi",
  "popupState": "Confira a página",
  "popupErrorTitle": "Não foi possível abrir",
  "popupErrorMessage": "Resolva o problema abaixo e tente novamente.",
  "opening": "Abrindo…",
  "goFollowing": "Abrir minha lista Seguindo",
  "popupReady": "Pronto · Aguardando a página",
  "popupTitle": "Abra sua lista Seguindo",
  "checking": "Verificando a página…",
  "preparing": "Preparando a limpeza",
  "checkingMessage": "Aguarde a verificação da página.",
  "pageState": "Estado da página",
  "helpOpen": "Use o botão para abrir sua lista Seguindo.",
  "helpLogin": "Se necessário, entre no X e clique novamente.",
  "helpPanel": "O painel aparece primeiro. Você pode analisar quando a lista carregar.",
  "popupFooter": "Detecta sua conta · Execução local",
  "navigationError": "Navegação indisponível",
  "fakeFriend": "Falso amigo",
  "needsCheck": "Verificar",
  "skipShort": "Pular",
  "backupMenu": "Backup e restauração",
  "exportBackup": "Exportar backup",
  "importKeep": "Importar lista de permissões",
  "keepImported": "Lista de permissões importada: {count} contas adicionadas. As decisões foram redefinidas; revise novamente.",
  "errorImportJson": "O arquivo de backup não é um JSON válido.",
  "errorImportFormat": "O formato da lista de permissões no backup é inválido.",
  "errorImportOwner": "O backup não contém a lista de permissões da conta atual. Escolha um arquivo exportado desta conta.",
  "removeKeep": "Remover",
  "keepEmpty": "A lista de permissões está vazia.",
  "keepRemoved": "@{handle} foi removido da lista de permissões e a alteração foi salva automaticamente.",
  "errorKeepProfile": "Os dados de avatar e nome da lista de permissões são inválidos.",
  "openingFollowing": "Abrindo sua lista Seguindo…",
  "errorExtensionReload": "A extensão foi recarregada ou removida. A tarefa anterior parou. Atualize o X.",
  "errorStalePanel": "Esta página ainda contém uma tarefa da extensão anterior. Atualize o X e reabra a extensão."
};
