export default {
  "resizePanel": "Vuta ukingo wa chini kurekebisha urefu",
  "errorPanelHeightSave": "Urefu wa paneli haukuweza kuhifadhiwa: {reason}",
  "waitingListUpdate": "Inasubiri X isasishe orodha. Maendeleo yamehifadhiwa.",
  "language": "Lugha",
  "panel": "Fake Friend",
  "subtitle": "Elewa uhusiano. Kisha amua.",
  "close": "Ficha paneli",
  "seen": "Akaunti zilizopatikana",
  "pending": "Zikaguliwe",
  "removed": "Ufuatiliaji umeondolewa",
  "countdown": "Zamu inayofuata",
  "loading": "Inapakia mipangilio…",
  "scan": "Kagua wanaofuatwa",
  "pause": "Sitisha",
  "resume": "Endelea",
  "stop": "Simamisha",
  "review": "Kagua moja moja",
  "controls": "Vidhibiti",
  "tabs": "Chaguo za usafishaji",
  "keep": "Za kuhifadhi",
  "settings": "Mipangilio",
  "list": "Zamu hii",
  "keepHint": "Kuongeza na kuondoa huhifadhiwa kiotomatiki.",
  "keepPlaceholder": "@akaunti_ya_kuhifadhi",
  "maxActions": "Kikomo cha kuacha kufuata",
  "skipFirst": "Ruka akaunti N za mwanzo",
  "scanMin": "Ukaguzi: sekunde chache",
  "scanMax": "Ukaguzi: sekunde nyingi",
  "unfollowMin": "Kuondoa: sekunde chache",
  "unfollowMax": "Kuondoa: sekunde nyingi",
  "autoScroll": "Sogeza orodha kiotomatiki",
  "pacingHint": "Kagua kutoka juu hadi chini. Muda mfupi na mrefu wa kusubiri hubadilishana kwa nasibu. Kusitisha huhifadhi maendeleo.",
  "reviewHint": "Kagua akaunti hii kwenye X. Kuidhinisha huiweka kwenye orodha; kuacha kufuata kutafanyika baadaye.",
  "reviewChanged": "Uhusiano umebadilika. Hifadhi au ruka akaunti hii.",
  "approve": "Ongeza kwenye usafishaji",
  "addKeep": "Ongeza za kuhifadhi",
  "skip": "Ruka",
  "start": "Anza usafishaji",
  "footer": "Kwenye kifaa · Uhusiano wa sasa",
  "export": "Hamisha kumbukumbu",
  "stayTitle": "Unaweza kubadilisha kichupo. Usipakie upya wala kuondoka kwenye ukurasa huu.",
  "empty": "Akaunti zitaonekana hapa baada ya ukaguzi.",
  "reviewPosition": "{current} / {total} · Ukaguzi",
  "executeCount": "Anza · {count} zimeidhinishwa",
  "unknown": "Akaunti isiyojulikana",
  "confirmed": "Imeidhinishwa",
  "skipped": "Imerukwa",
  "protected": "Imerukwa mwanzo",
  "seconds": "Sekunde {count}",
  "scanFirst": "Kagua orodha, kisha hakiki kila akaunti.",
  "skipChanged": "Idadi ya kuruka imebadilika. Kagua tena.",
  "keepSaved": "Orodha imehifadhiwa. Hakiki tena orodha ya usafishaji.",
  "reviewDone": "Akaunti {count} zimeidhinishwa. Anza usafishaji ili kuacha kuzifuata.",
  "locating": "Inatafuta @{handle}…",
  "located": "@{handle} imepatikana. Kagua kwenye X.",
  "decisionSaved": "Chaguo la @{handle} limehifadhiwa. Zimebaki {count}.",
  "locatingPaused": "Utafutaji umesitishwa.",
  "scanned": "Akaunti {count} zimepatikana.",
  "scannedSkip": "Akaunti {count} zimepatikana; {skip} za mwanzo zimerukwa.",
  "processing": "Inashughulikia @{handle}…",
  "removedUser": "Umeacha kufuata @{handle}.",
  "skippedUser": "@{handle} imerukwa.",
  "nextRound": "Zamu inayofuata baada ya sekunde {count}.",
  "finishedMax": "Kikomo cha kuacha kufuata kimefikiwa.",
  "finishedVisible": "Akaunti zilizopakiwa zimeshughulikiwa.",
  "finishedEnd": "Mwisho wa orodha inayopatikana. Kazi imekamilika.",
  "finishedApproved": "Kundi hili limekamilika. Unaweza kuchagua akaunti zaidi.",
  "resumed": "Imeendelezwa.",
  "paused": "Imesitishwa.",
  "stopped": "Imesimamishwa.",
  "waitEnd": "Inakagua mwisho ({count}/2).",
  "errorBusy": "Maliza au simamisha kitendo cha sasa.",
  "errorMode": "Kitendo batili.",
  "errorReview": "Kagua akaunti kabla ya kuanza.",
  "errorNoResume": "Hakuna kazi iliyositishwa ya kuendelea nayo.",
  "errorAccount": "Akaunti iliyoingia imebadilika. Imesimamishwa.",
  "errorLoading": "Data bado inapakiwa. Subiri kisha kagua tena.",
  "errorPage": "Fungua orodha yako ya unaowafuata kwenye X.",
  "errorPageStructure": "Orodha haijatambuliwa. Pakia X upya na ujaribu tena.",
  "errorButton": "Kitufe cha akaunti hakijatambuliwa.",
  "errorIdentity": "Utambulisho wa akaunti haulingani.",
  "errorDialog": "Dirisha la kuthibitisha halijahakikiwa. Imesimamishwa.",
  "errorOtherDialog": "Funga dirisha lililo wazi kwanza.",
  "errorMoved": "Akaunti imebadilika au imehamia. Kagua tena.",
  "errorChanged": "Uhusiano umebadilika. Hifadhi au ruka akaunti.",
  "errorUnconfirmed": "Matokeo hayajathibitishwa. Kagua X kabla ya kujaribu tena.",
  "errorScroll": "Kusogeza hakujakamilika. Imesimamishwa.",
  "errorTop": "Haikurudi juu. Kagua ukurasa.",
  "errorLoadTimeout": "Upakiaji haujakamilika. Mwisho haujathibitishwa.",
  "errorStuck": "Ukurasa haukusogea. Ukaguzi umesimamishwa.",
  "errorRange": "Sekunde nzima: 1 ≤ chini < juu ≤ 10000.",
  "errorRandom": "Muda wa kusubiri haukuchaguliwa. Imesimamishwa.",
  "errorSkipRange": "Idadi ya kuruka iwe namba nzima 0–10000.",
  "errorActionRange": "Kikomo kiwe namba nzima 1–10000.",
  "errorAutoScroll": "Chagua kama ukurasa usogezwe kiotomatiki.",
  "errorStorage": "Mipangilio ya kifaa si sahihi. Kagua hifadhi.",
  "errorNoAudit": "Kumbukumbu ya shughuli haijaanzishwa.",
  "errorCurrent": "Kagua akaunti inayoonyeshwa.",
  "errorNotListed": "Akaunti hii haipo kwenye orodha ya sasa.",
  "errorNoCandidates": "Hakuna akaunti za kukagua.",
  "errorEmpty": "Orodha iliyoidhinishwa ni tupu.",
  "errorInvalidHandle": "Jina la akaunti si sahihi: {value}",
  "errorPageAlert": "Imesimamishwa — X imesema: {reason}",
  "errorOutcome": "Kitufe cha kuacha kufuata kimebonyezwa; matokeo hayajathibitishwa: {reason}",
  "errorSave": "Kumbukumbu haikuhifadhiwa: {reason}",
  "errorMissingHandle": "@{handle} haipatikani. Kagua tena.",
  "errorNavigation": "Ukurasa haukufunguka. Pakia X upya.",
  "errorLogin": "Ingia X, subiri ukurasa, kisha jaribu tena.",
  "errorLeft": "Umeondoka kwenye ukurasa. Uhamaji umeghairiwa.",
  "acknowledge": "Nimeelewa",
  "popupState": "Kagua ukurasa",
  "popupErrorTitle": "Haiwezi kufungua",
  "popupErrorMessage": "Tatua tatizo lililo hapa chini, kisha jaribu tena.",
  "opening": "Inafungua…",
  "goFollowing": "Fungua orodha ninayofuata",
  "popupReady": "Tayari · Inasubiri ukurasa",
  "popupTitle": "Fungua orodha yako ya unaowafuata",
  "checking": "Inakagua ukurasa…",
  "preparing": "Inaandaa usafishaji",
  "checkingMessage": "Subiri ukurasa ukaguliwe.",
  "pageState": "Hali ya ukurasa",
  "helpOpen": "Tumia kitufe kufungua orodha yako ya unaowafuata.",
  "helpLogin": "Kama hujaingia X, ingia kisha bonyeza tena.",
  "helpPanel": "Paneli inaonekana kwanza. Unaweza kuchanganua orodha ikishapakiwa.",
  "popupFooter": "Hutambua akaunti · Hufanya kazi kwenye kifaa",
  "navigationError": "Haiwezi kubadili ukurasa",
  "fakeFriend": "Rafiki bandia",
  "needsCheck": "Inahitaji ukaguzi",
  "skipShort": "Ruka",
  "backupMenu": "Nakala na urejeshaji",
  "exportBackup": "Hamisha nakala rudufu",
  "importKeep": "Ingiza orodha iliyoidhinishwa",
  "keepImported": "Orodha imeingizwa: akaunti {count} zimeongezwa. Maamuzi ya ukaguzi yamewekwa upya; kagua tena.",
  "errorImportJson": "Faili ya nakala rudufu si JSON halali.",
  "errorImportFormat": "Muundo wa orodha iliyoidhinishwa kwenye nakala rudufu si halali.",
  "errorImportOwner": "Nakala rudufu haina orodha iliyoidhinishwa ya akaunti hii. Chagua faili iliyohamishwa kutoka akaunti hii.",
  "removeKeep": "Ondoa",
  "keepEmpty": "Hakuna akaunti kwenye orodha iliyoidhinishwa bado.",
  "keepRemoved": "@{handle} imeondolewa kwenye orodha iliyoidhinishwa na mabadiliko yamehifadhiwa kiotomatiki.",
  "errorKeepProfile": "Data ya picha na majina katika orodha iliyoidhinishwa si halali.",
  "openingFollowing": "Inafungua orodha ya unaowafuata…",
  "errorExtensionReload": "Kiendelezi kimepakiwa upya au kuondolewa. Kazi ya zamani imesimama. Pakia X upya.",
  "errorStalePanel": "Ukurasa huu bado una kazi ya toleo la zamani la kiendelezi. Pakia X upya, kisha ufungue kiendelezi tena."
};
