export default {
  "resizePanel": "Kéo cạnh dưới để chỉnh chiều cao",
  "errorPanelHeightSave": "Không thể lưu chiều cao bảng: {reason}",
  "waitingListUpdate": "Đang chờ X cập nhật danh sách. Tiến độ được giữ lại.",
  "language": "Ngôn ngữ",
  "panel": "Fake Friend",
  "subtitle": "Hiểu mối liên hệ. Tự mình quyết định.",
  "close": "Ẩn bảng điều khiển",
  "seen": "Tài khoản tìm thấy",
  "pending": "Chờ xác nhận",
  "removed": "Đã bỏ theo dõi",
  "countdown": "Lượt tiếp theo",
  "loading": "Đang tải cài đặt…",
  "scan": "Quét danh sách",
  "pause": "Tạm dừng",
  "resume": "Tiếp tục",
  "stop": "Dừng",
  "review": "Xác nhận từng người",
  "controls": "Điều khiển",
  "tabs": "Tùy chọn dọn dẹp",
  "keep": "Giữ lại",
  "settings": "Cài đặt",
  "list": "Lượt này",
  "keepHint": "Việc thêm và xóa được lưu tự động.",
  "keepPlaceholder": "@tài_khoản_giữ_lại",
  "maxActions": "Giới hạn bỏ theo dõi",
  "skipFirst": "Bỏ qua N người đầu",
  "scanMin": "Quét tối thiểu / giây",
  "scanMax": "Quét tối đa / giây",
  "unfollowMin": "Bỏ theo dõi tối thiểu / giây",
  "unfollowMax": "Bỏ theo dõi tối đa / giây",
  "autoScroll": "Tự động cuộn danh sách",
  "pacingHint": "Quét từ đầu đến cuối. Thời gian chờ ngẫu nhiên luân phiên ngắn và dài. Tạm dừng giữ tiến độ.",
  "reviewHint": "Kiểm tra tài khoản trên X. Xác nhận chỉ thêm vào danh sách; việc bỏ theo dõi diễn ra sau.",
  "reviewChanged": "Quan hệ đã thay đổi. Hãy giữ lại hoặc bỏ qua.",
  "approve": "Thêm vào danh sách dọn",
  "addKeep": "Thêm vào danh sách giữ",
  "skip": "Bỏ qua",
  "start": "Bắt đầu dọn",
  "footer": "Chạy cục bộ · Quan hệ hiện tại",
  "export": "Xuất nhật ký",
  "stayTitle": "Có thể chuyển tab. Đừng tải lại hoặc rời trang này.",
  "empty": "Tài khoản cần xem sẽ hiện ở đây sau khi quét.",
  "reviewPosition": "{current} / {total} · Xác nhận",
  "executeCount": "Bắt đầu · Đã duyệt {count}",
  "unknown": "Tài khoản chưa rõ",
  "confirmed": "Đã duyệt",
  "skipped": "Đã bỏ qua",
  "protected": "Bỏ qua từ đầu",
  "seconds": "{count} giây",
  "scanFirst": "Quét danh sách, rồi xác nhận từng tài khoản.",
  "skipChanged": "Số lượng bỏ qua đã đổi. Hãy quét và xác nhận lại.",
  "keepSaved": "Đã lưu danh sách giữ. Xác nhận lại danh sách dọn.",
  "reviewDone": "Đã duyệt {count} tài khoản. Chọn Bắt đầu dọn để bỏ theo dõi.",
  "locating": "Đang tìm @{handle}…",
  "located": "Đã tìm thấy @{handle}. Kiểm tra trên X.",
  "decisionSaved": "Đã lưu lựa chọn @{handle}. Còn {count} tài khoản.",
  "locatingPaused": "Đã tạm dừng tìm tài khoản.",
  "scanned": "Tìm thấy {count} tài khoản.",
  "scannedSkip": "Tìm thấy {count} tài khoản; bỏ qua {skip} người đầu.",
  "processing": "Đang xử lý @{handle}…",
  "removedUser": "Đã bỏ theo dõi @{handle}.",
  "skippedUser": "Đã bỏ qua @{handle}.",
  "nextRound": "Lượt tiếp theo sau {count} giây.",
  "finishedMax": "Đã đạt giới hạn bỏ theo dõi.",
  "finishedVisible": "Đã xử lý tài khoản được tải.",
  "finishedEnd": "Đã đến cuối danh sách hiện có. Hoàn tất.",
  "finishedApproved": "Đã xử lý xong đợt này. Bạn có thể chọn thêm tài khoản.",
  "resumed": "Đã tiếp tục.",
  "paused": "Đã tạm dừng.",
  "stopped": "Đã dừng.",
  "waitEnd": "Đang kiểm tra cuối danh sách ({count}/2).",
  "errorBusy": "Hãy hoàn thành hoặc dừng thao tác hiện tại.",
  "errorMode": "Thao tác không hợp lệ.",
  "errorReview": "Xác nhận tài khoản trước khi bắt đầu.",
  "errorNoResume": "Không có lượt tạm dừng để tiếp tục.",
  "errorAccount": "Tài khoản đăng nhập đã đổi. Đã dừng.",
  "errorLoading": "Dữ liệu đang tải. Chờ rồi quét lại.",
  "errorPage": "Mở danh sách Đang theo dõi của chính bạn trên X.",
  "errorPageStructure": "Không nhận diện được danh sách. Tải lại X và thử lại.",
  "errorButton": "Không nhận diện được nút của tài khoản.",
  "errorIdentity": "Danh tính tài khoản không khớp.",
  "errorDialog": "Không xác minh được hộp thoại xác nhận. Đã dừng.",
  "errorOtherDialog": "Đóng hộp thoại đang mở trước khi tiếp tục.",
  "errorMoved": "Tài khoản đã đổi hoặc di chuyển. Quét lại.",
  "errorChanged": "Quan hệ đã đổi. Giữ lại hoặc bỏ qua tài khoản.",
  "errorUnconfirmed": "Kết quả chưa xác nhận. Kiểm tra trên X trước khi thử lại.",
  "errorScroll": "Cuộn chưa hoàn tất. Đã dừng.",
  "errorTop": "Không trở về đầu trang được. Hãy kiểm tra trang.",
  "errorLoadTimeout": "Danh sách chưa tải xong. Chưa xác nhận cuối danh sách.",
  "errorStuck": "Trang không cuộn xuống. Đã dừng quét.",
  "errorRange": "Giây nguyên: 1 ≤ tối thiểu < tối đa ≤ 10000.",
  "errorRandom": "Không chọn được thời gian chờ. Đã dừng.",
  "errorSkipRange": "Số bỏ qua phải là số nguyên từ 0 đến 10000.",
  "errorActionRange": "Giới hạn phải là số nguyên từ 1 đến 10000.",
  "errorAutoScroll": "Chọn có tự động cuộn hay không.",
  "errorStorage": "Cài đặt cục bộ không hợp lệ. Kiểm tra bộ nhớ tiện ích.",
  "errorNoAudit": "Chưa tạo nhật ký hoạt động.",
  "errorCurrent": "Hãy xác nhận tài khoản đang hiển thị.",
  "errorNotListed": "Tài khoản không thuộc danh sách hiện tại.",
  "errorNoCandidates": "Không có tài khoản cần xác nhận.",
  "errorEmpty": "Danh sách được duyệt đang trống.",
  "errorInvalidHandle": "Tên tài khoản không hợp lệ: {value}",
  "errorPageAlert": "Đã dừng — thông báo từ X: {reason}",
  "errorOutcome": "Đã bấm bỏ theo dõi; kết quả chưa xác nhận: {reason}",
  "errorSave": "Không lưu được nhật ký: {reason}",
  "errorMissingHandle": "Không tìm thấy @{handle}. Quét lại.",
  "errorNavigation": "Không mở được trang. Tải lại X và thử lại.",
  "errorLogin": "Đăng nhập X, chờ trang tải, rồi thử lại.",
  "errorLeft": "Bạn đã rời trang. Đã hủy chuyển trang.",
  "acknowledge": "Đã hiểu",
  "popupState": "Kiểm tra trang",
  "popupErrorTitle": "Không mở được",
  "popupErrorMessage": "Khắc phục vấn đề bên dưới rồi thử lại.",
  "opening": "Đang mở…",
  "goFollowing": "Mở danh sách theo dõi",
  "popupReady": "Sẵn sàng · Đang chờ trang",
  "popupTitle": "Mở danh sách theo dõi của bạn",
  "checking": "Đang kiểm tra trang…",
  "preparing": "Đang chuẩn bị bảng dọn dẹp",
  "checkingMessage": "Vui lòng chờ kiểm tra trang.",
  "pageState": "Trạng thái trang",
  "helpOpen": "Dùng nút bên dưới để mở danh sách theo dõi của bạn.",
  "helpLogin": "Nếu chưa đăng nhập X, hãy đăng nhập rồi bấm lại.",
  "helpPanel": "Bảng điều khiển hiện trước. Bạn có thể quét khi danh sách tải xong.",
  "popupFooter": "Nhận diện tài khoản · Chạy cục bộ",
  "navigationError": "Không chuyển trang được",
  "fakeFriend": "Bạn giả",
  "needsCheck": "Cần kiểm tra",
  "skipShort": "Bỏ qua",
  "backupMenu": "Sao lưu và khôi phục",
  "exportBackup": "Xuất bản sao lưu",
  "importKeep": "Nhập danh sách trắng",
  "keepImported": "Đã nhập danh sách trắng, thêm {count} tài khoản. Các lựa chọn đã được đặt lại; vui lòng duyệt lại.",
  "errorImportJson": "Tệp sao lưu không phải JSON hợp lệ.",
  "errorImportFormat": "Định dạng danh sách trắng trong bản sao lưu không hợp lệ.",
  "errorImportOwner": "Bản sao lưu không có danh sách trắng của tài khoản hiện tại. Hãy chọn tệp được xuất từ tài khoản này.",
  "removeKeep": "Xóa",
  "keepEmpty": "Danh sách trắng chưa có tài khoản nào.",
  "keepRemoved": "Đã xóa @{handle} khỏi danh sách trắng và tự động lưu thay đổi.",
  "errorKeepProfile": "Dữ liệu ảnh đại diện và tên trong danh sách trắng không hợp lệ.",
  "openingFollowing": "Đang mở danh sách Đang theo dõi…",
  "errorExtensionReload": "Tiện ích đã được tải lại hoặc gỡ bỏ. Tác vụ cũ đã dừng. Hãy tải lại X.",
  "errorStalePanel": "Trang này vẫn còn tác vụ của tiện ích cũ. Tải lại X rồi mở lại tiện ích."
};
