export default {
  "waitingListUpdate": "等待 X 更新列表，进度已保留。",
  "language": "语言",
  "panel": "Fake Friend",
  "subtitle": "看清关系，再做决定。",
  "close": "隐藏面板",
  "seen": "已识别账号",
  "pending": "待确认",
  "removed": "已取关",
  "countdown": "倒计时",
  "loading": "读取本地设置…",
  "scan": "扫描关注列表",
  "pause": "暂停",
  "resume": "继续",
  "stop": "停止",
  "review": "逐个确认",
  "controls": "本轮控制",
  "tabs": "面板内容",
  "keep": "白名单",
  "settings": "运行设置",
  "list": "本轮名单",
  "keepHint": "加入和移除都会自动保存。",
  "keepPlaceholder": "@想继续关注的人",
  "maxActions": "本轮最多取关 / 人",
  "skipFirst": "跳过列表前 N 人",
  "scanMin": "扫描最短间隔 / 秒",
  "scanMax": "扫描最长间隔 / 秒",
  "unfollowMin": "取关最短间隔 / 秒",
  "unfollowMax": "取关最长间隔 / 秒",
  "autoScroll": "扫描和执行时自动向下滚动",
  "pacingHint": "从顶部扫到末尾。等待时长在高低两档交替随机，轮内正常倒数。暂停保留进度。",
  "reviewHint": "已在 X 页面定位此人。确认只加入名单，稍后统一执行。",
  "reviewChanged": "此人的关注关系已变化，请保留或跳过。",
  "approve": "加入清理名单",
  "addKeep": "加入白名单",
  "skip": "这次跳过",
  "start": "开始执行",
  "footer": "本地运行 · 当前关系判断",
  "export": "导出操作记录",
  "stayTitle": "可切换标签，请勿刷新或跳转。",
  "empty": "扫描后，待处理账号会出现在这里。",
  "reviewPosition": "{current} / {total} · 逐个核对",
  "executeCount": "开始执行 · 已确认 {count} 人",
  "unknown": "未识别账号",
  "confirmed": "已确认",
  "skipped": "已跳过",
  "protected": "前 N 人跳过",
  "seconds": "{count} 秒",
  "scanFirst": "先扫描名单，再逐个定位确认。",
  "skipChanged": "跳过范围已改变，请重新扫描，再逐个确认。",
  "keepSaved": "白名单已保存。确认名单已重置，请重新逐个确认。",
  "reviewDone": "本轮选择已完成：{count} 人加入清理名单。点击“开始执行”后才会取关。",
  "locating": "正在翻页定位 @{handle}…",
  "located": "已定位 @{handle}，请在原页面核对。",
  "decisionSaved": "已记录 @{handle} 的选择，还剩 {count} 人待确认。",
  "locatingPaused": "定位已暂停。",
  "scanned": "已识别 {count} 个账号。",
  "scannedSkip": "已识别 {count} 个账号，前 {skip} 人已跳过。",
  "processing": "正在处理 @{handle}…",
  "removedUser": "已取关 @{handle}。",
  "skippedUser": "已跳过 @{handle}。",
  "nextRound": "下一轮 {count} 秒后。",
  "finishedMax": "已到本轮取关数量上限。",
  "finishedVisible": "当前已加载区域处理完毕。",
  "finishedEnd": "已到当前可加载列表末尾。本轮结束。",
  "finishedApproved": "本批已处理完成，可继续选择其他账号。",
  "resumed": "已继续。",
  "paused": "已暂停。",
  "stopped": "本轮已停止。",
  "waitEnd": "正在确认列表末尾（{count}/2）。",
  "errorBusy": "请先完成或停止当前操作。",
  "errorMode": "无效操作。",
  "errorReview": "请先逐个确认需要处理的账号。",
  "errorNoResume": "当前没有可继续的暂停任务。",
  "errorAccount": "登录账号已变化，已停止。",
  "errorLoading": "账号资料尚未加载完整，请等待后重新扫描。",
  "errorPage": "请打开自己账号的“正在关注”列表。",
  "errorPageStructure": "无法识别关注列表，请刷新 X 页面后重试。",
  "errorButton": "无法识别账号的关注按钮。",
  "errorIdentity": "账号身份不一致。",
  "errorDialog": "无法确认取关弹窗，已停止。",
  "errorOtherDialog": "页面已有其他弹窗，请先处理后再开始。",
  "errorMoved": "账号已移动或变化，请重新扫描。",
  "errorChanged": "关注关系已变化，请保留或跳过。",
  "errorUnconfirmed": "取关结果未确认，请先在 X 页面核对。",
  "errorScroll": "页面滚动未完成，已停止。",
  "errorTop": "未能回到列表顶部，请检查页面。",
  "errorLoadTimeout": "列表加载未完成，尚未确认到达末尾。",
  "errorStuck": "页面滚动没有前进，扫描已停止。",
  "errorRange": "间隔使用整数秒，满足 1 ≤ 最小值 < 最大值 ≤ 10000。",
  "errorRandom": "随机间隔取值失败，已停止。",
  "errorSkipRange": "跳过人数须为 0～10000 的整数。",
  "errorActionRange": "取关上限须为 1～10000 的整数。",
  "errorAutoScroll": "请选择是否自动滚动。",
  "errorStorage": "本地配置格式不正确，请检查扩展存储。",
  "errorNoAudit": "尚未建立本轮操作记录。",
  "errorCurrent": "只能确认当前展示的账号。",
  "errorNotListed": "该账号不在本轮名单中。",
  "errorNoCandidates": "当前没有需要确认的账号。",
  "errorEmpty": "确认名单为空。",
  "errorInvalidHandle": "无效账号：{value}",
  "errorPageAlert": "页面提示，已停止：{reason}",
  "errorOutcome": "已点击取关，结果未确认：{reason}",
  "errorSave": "记录保存失败：{reason}",
  "errorMissingHandle": "无法定位 @{handle}，请重新扫描。",
  "errorNavigation": "页面打开失败，请刷新 X 页面后重试。",
  "errorLogin": "请先登录 X，等待加载后重试。",
  "errorLeft": "已离开页面，取消跳转。",
  "acknowledge": "知道了",
  "popupState": "需要处理页面状态",
  "popupErrorTitle": "暂时无法打开",
  "popupErrorMessage": "请查看下面的原因，处理后再试。",
  "opening": "正在打开…",
  "goFollowing": "前往我的关注列表",
  "popupReady": "插件已就绪 · 等待切换页面",
  "popupTitle": "请先打开关注列表",
  "checking": "正在检查页面…",
  "preparing": "准备打开清理面板",
  "checkingMessage": "稍等片刻，正在确认当前页面。",
  "pageState": "当前页面状态",
  "helpOpen": "点击下方按钮，自动前往自己的关注列表。",
  "helpLogin": "若未登录 X，请先登录，再点一次按钮。",
  "helpPanel": "先显示面板，列表加载后即可扫描。",
  "popupFooter": "自动识别当前账号 · 本地运行",
  "navigationError": "暂时无法跳转",
  "fakeFriend": "假朋友",
  "needsCheck": "待检查",
  "skipShort": "跳过",
  "backupMenu": "备份与恢复",
  "exportBackup": "导出备份",
  "importKeep": "导入白名单",
  "keepImported": "白名单已导入，新增 {count} 人。确认名单已重置，请重新逐个确认。",
  "errorImportJson": "备份文件不是有效的 JSON。",
  "errorImportFormat": "备份白名单格式不正确。",
  "errorImportOwner": "备份中没有当前登录账号的白名单，请选择这个账号导出的文件。",
  "removeKeep": "移除",
  "keepEmpty": "暂无白名单。",
  "keepRemoved": "@{handle} 已移出白名单，已自动保存。",
  "errorKeepProfile": "白名单头像和名称资料格式不正确。",
  "openingFollowing": "正在打开关注列表…",
  "errorExtensionReload": "插件已重新加载或被移除，旧任务已停止。请刷新 X 页面。",
  "errorStalePanel": "页面仍有旧版插件任务，请刷新 X 页面后重新打开插件。"
};
